<a href="https://colab.research.google.com/github/Ashking1981/lb_training/blob/master/Tensorflow_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 2 Introduction

Tensorflow 2.x alongwith Keras API provide a powerful set of tools to write Neural Networks, test and deploy them in a jiffy.

The official documentation could be found here : https://www.tensorflow.org/

---
### TensorFlow 2.0 is an extensive redesign of TensorFlow and Keras that takes into account over four years of user feedback and technical progress.
---

TensorFlow 2.0 is built on the following key ideas:

- Let users run their computation eagerly, like they would in Numpy. This makes TensorFlow 2.0 programming intuitive and Pythonic.
- Preserve the considerable advantages of compiled graphs (for performance, distribution, and deployment). This makes TensorFlow fast, scalable, and production-ready.
- Leverage Keras as its high-level deep learning API, making TensorFlow approachable and highly productive.
- Extend Keras into a spectrum of workflows ranging from the very high-level (easier to use, less flexible) to the very low-level (requires more expertise, but provides great flexibility).

### Easy model building
TensorFlow offers multiple levels of abstraction so you can choose the right one for your needs. Build and train models by using the high-level Keras API, which makes getting started with TensorFlow and machine learning easy.

If you need more flexibility, eager execution allows for immediate iteration and intuitive debugging. For large ML training tasks, use the Distribution Strategy API for distributed training on different hardware configurations without changing the model definition.

### Robust ML production anywhere
TensorFlow has always provided a direct path to production. Whether it’s on servers, edge devices, or the web, TensorFlow lets you train and deploy your model easily, no matter what language or platform you use.

Use TensorFlow Extended (TFX) if you need a full production ML pipeline. For running inference on mobile and edge devices, use TensorFlow Lite. Train and deploy models in JavaScript environments using TensorFlow.js.

### Powerful experimentation for research
Build and train state-of-the-art models without sacrificing speed or performance. TensorFlow gives you the flexibility and control with features like the Keras Functional API and Model Subclassing API for creation of complex topologies. For easy prototyping and fast debugging, use eager execution.

TensorFlow also supports an ecosystem of powerful add-on libraries and models to experiment with, including Ragged Tensors, TensorFlow Probability, Tensor2Tensor and BERT.

In [ ]:
'''
!pip install --upgrade tensorflow  # cpu only
!pip install --upgrade tensorflow-gpu # gpu and cpu
'''

'\n!pip install --upgrade tensorflow  # cpu only\n!pip install --upgrade tensorflow-gpu # gpu and cpu\n'

In [ ]:
# check the version
import tensorflow as tf
print(('Your TensorFlow version: {0}').format(tf.__version__))

Your TensorFlow version: 2.15.0


In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
2+2

4

How to verify if running eager execution?

Eager execution is a fairly new addition to the tensorflow framework, thus we wish to check if eager execution is enabled or disabled.

In [ ]:
if(tf.executing_eagerly()):
    print('Eager execution is enabled (running operations immediately)\n')
    print(('Turn eager execution off by running: \n{0}\n{1}').format('' \
        'from tensorflow.python.framework.ops import disable_eager_execution', \
        'disable_eager_execution()'))
else:
    print('You are not running eager execution. TensorFlow version >= 2.0.0' \
          'has eager execution enabled by default.')
    print(('Turn on eager execution by running: \n\n{0}\n\nOr upgrade '\
           'your tensorflow version by running:\n\n{1}').format(
           'tf.compat.v1.enable_eager_execution()'))

Eager execution is enabled (running operations immediately)

Turn eager execution off by running: 
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()


Verify if GPU is available and ready to be used

In [ ]:
print(('Is your GPU available for use? \n{0}').format(
    'Yes, your GPU is available: True' if tf.test.is_gpu_available() == True else 'No, your GPU is NOT available: False'
))

print(('\nYour devices that are available:\n{0}').format(
    [device.name for device in tf.config.list_physical_devices('GPU')]
))

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Is your GPU available for use? 
Yes, your GPU is available: True

Your devices that are available:
['/physical_device:GPU:0']


In [ ]:
print(tf.config.list_physical_devices('CPU'))

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [ ]:
! nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-63a4d633-7116-9238-7f20-4becd31480d7)


In [ ]:
! nvidia-smi

Thu Mar 28 15:03:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P0              26W /  70W |    103MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Check the runtime comparison

In [ ]:
import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.reduce_sum(random_image_cpu)

    # Printing how long it took with CPU
    end_cpu = time.time() - start
    print(end_cpu)

# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on GPU
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.reduce_sum(random_image_gpu)

    # Printing how long it took with GPU
    end_gpu = time.time() - start
    print(end_gpu)
print('GPU speedup over CPU: {}x'.format(int(end_cpu/end_gpu)))

0.05357694625854492
0.0018322467803955078
GPU speedup over CPU: 29x


Basic Datatypes

**Constant**


In [ ]:
c = tf.constant(4.0, dtype=tf.float64)
c.dtype

tf.float64

In [ ]:
print(c)

tf.Tensor(4.0, shape=(), dtype=float64)


In [ ]:
import numpy as np
d = np.array([ [1,2,3], [4,5,6]])
d.dtype

dtype('int64')

In [ ]:
e = tf.constant(d)
print(e)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [ ]:
e.dtype

tf.int64

In [ ]:
b = tf.constant( [1,0,1])
print (b)
b = tf.expand_dims(b,1)
b.shape
b

tf.Tensor([1 0 1], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [0],
       [1]], dtype=int32)>

In [ ]:
tf.random.normal(shape=(10,10), mean=0., stddev=1.)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.12573062,  0.46320528,  0.7029934 , -1.7764504 , -0.34857577,
        -0.7954146 , -1.0305321 ,  1.025787  ,  0.60246646,  0.61368006],
       [ 0.70741904,  0.5353028 ,  0.18150899,  0.1629454 , -0.3487283 ,
         0.0109113 ,  1.2978622 ,  0.23553881, -1.2931772 , -0.37972566],
       [-0.40261292,  0.56782436,  0.5413016 , -0.07257798, -1.3578783 ,
        -2.5503192 ,  1.0281583 , -1.1387393 , -1.4759257 , -1.0458381 ],
       [-0.7116127 , -0.04017811,  0.12178895, -0.29131275,  0.54015446,
        -0.3966985 ,  1.2635022 ,  0.6463509 ,  1.1337544 , -0.02937857],
       [-2.4938483 ,  0.6688465 , -0.76765645,  1.3197142 ,  0.6072693 ,
         1.4456718 ,  0.94113845, -1.6337845 ,  0.07544285,  1.1286925 ],
       [ 0.666254  , -0.49752256,  0.85845774,  1.3763189 ,  0.64929974,
         1.1104733 , -0.01741618, -0.10869764, -1.4899554 , -1.3056877 ],
       [ 0.49510378,  0.40816957, -0.31648666, -1.4267706 , -0.65686

In [ ]:
tf.random.uniform(shape=(10, 10), minval=0, maxval=10, dtype='int32')

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[6, 9, 4, 9, 2, 5, 1, 2, 0, 2],
       [8, 1, 7, 5, 4, 3, 9, 8, 9, 7],
       [5, 4, 4, 7, 0, 8, 1, 6, 8, 2],
       [1, 0, 8, 5, 6, 5, 2, 8, 7, 3],
       [5, 9, 6, 2, 3, 5, 0, 7, 7, 3],
       [2, 8, 2, 0, 7, 8, 7, 4, 1, 0],
       [8, 9, 3, 8, 1, 9, 5, 1, 2, 4],
       [2, 5, 8, 1, 8, 2, 5, 4, 4, 0],
       [1, 1, 8, 4, 1, 5, 9, 6, 9, 5],
       [4, 1, 9, 9, 4, 7, 9, 9, 1, 4]], dtype=int32)>

**Variables**

In [ ]:
init_vals = tf.random.normal((1,5),0,1)
var = tf.Variable(init_vals)
print(var)

<tf.Variable 'Variable:0' shape=(1, 5) dtype=float32, numpy=
array([[ 0.21268356, -0.09350217, -1.7980757 ,  1.8558645 , -0.9391016 ]],
      dtype=float32)>


In [ ]:
var.dtype

tf.float32

We update the value of a Variable by using the methods .assign(value), or .assign_add(increment) or .assign_sub(decrement):

In [ ]:
initial_value = tf.random.normal(shape=(2, 2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.1365942, -0.3197508],
       [-0.6115111, -0.9428835]], dtype=float32)>


In [ ]:
new_value = tf.random.normal(shape=(2, 2))
print(new_value)
a.assign(new_value)
for i in range(2):
  for j in range(2):
    assert a[i, j] == new_value[i, j]

tf.Tensor(
[[ 0.6933254   0.8489087 ]
 [-0.17245397  0.21287769]], shape=(2, 2), dtype=float32)


In [ ]:
print (a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.6933254 ,  0.8489087 ],
       [-0.17245397,  0.21287769]], dtype=float32)>


In [ ]:
print(new_value)

tf.Tensor(
[[ 0.6933254   0.8489087 ]
 [-0.17245397  0.21287769]], shape=(2, 2), dtype=float32)


In [ ]:
added_value = tf.random.normal(shape=(2, 2))
a.assign_add(added_value)
for i in range(2):
  for j in range(2):
    assert a[i, j] == new_value[i, j] + added_value[i, j]

In [ ]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2.3966696, 2.1584718],
       [1.5527835, 0.5299032]], dtype=float32)>


In [ ]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

c = a + b
d = tf.square(c)
e = tf.exp(d)

In [ ]:
print (c,d,e)

tf.Tensor(
[[ 0.6986246  -0.04489219]
 [-0.4582258   1.0418181 ]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0.48807636 0.00201531]
 [0.20997088 1.0853851 ]], shape=(2, 2), dtype=float32) tf.Tensor(
[[1.6291792 1.0020174]
 [1.2336421 2.9605796]], shape=(2, 2), dtype=float32)


**Simple Operations**

We need to know the basic operations in tensorflow, in order to be able to use tensorflow for most of our work.

**Common Use**

This is some of the common functions from tensorflow, that you will probably need to use at some point.

* Making tensors tf.constant and tf.Variable

* Concatenation of two tensors by tf.concat

* Making tensors by tf.zeros or tf.ones

* Reshape data by tf.reshape

* Casting tensors to other data types by tf.cast

Concatenation by tf.concat and making tensors by tf.constant

In [ ]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

# Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(
    AB_concatenated.numpy()
))

# Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{0}').format(
    AB_concatenated.numpy()
))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]

Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [ ]:
A = B

In [ ]:
print (A)

tf.Tensor(
[[9 5]
 [1 3]], shape=(2, 2), dtype=int32)


In [ ]:
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 2],
       [9, 5],
       [1, 3]], dtype=int32)>

Making tensors by tf.zeros and tf.ones


In [ ]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor=tensor,
                            shape=[1, 8])

print(('Tensor BEFORE reshape:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor AFTER reshape:\n{0}').format(
    reshaped_tensor.numpy()
))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


In [ ]:
# Making a tensor
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]],
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

print(('Tensor with floats:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(
    tensor_as_int.numpy()
))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


### The linear algebra operations
* Transpose tensor
* Matrix Multiplication
* Element-wise multiplication
* Identity Matrix
* Determinant
* Dot Product

In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
    A
))

The transposed matrix A:
[[3 1]
 [7 9]]


In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Some vector v
v = tf.constant([[5],
                 [2]])

# Matrix multiplication of A.v^T
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


In [ ]:
# Element-wise multiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(
    rows, columns
))

# Making identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(
    A_identity.numpy()
))

Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


In [ ]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(
    det_A
))

The determinant of A:
20.000001907348633


In [ ]:
# Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                 [91, 10, 95],
                 [37, 13, 45]])

# Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(
    dot_AB
))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(
    AB
))

Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]

Matrix Multiplication of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


### Calculating Gradients
When using gradient tape from TensorFlow, we need to create a tf.Variable and not tf.constant, because TensorFlow does not watch constants. The great thing about making variables is that we can use gradient tape at any time, and TensorFlow will automatically give us the gradient.

In [ ]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

print(a)
print(b)

with tf.GradientTape() as tape:
  tape.watch(a)  # Start recording the history of operations applied to `a`
  c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
  print (c)
  # What's the gradient of `c` with respect to `a`?
  dc_da = tape.gradient(c, a)
  print(dc_da)
#   dc_db= tape.gradient(c, b)
#   print(dc_db)

tf.Tensor(
[[-0.8231844  -1.2216929 ]
 [ 0.62805235  2.812102  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.7565386  0.4451168 ]
 [1.2582619  0.01776371]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.1180265 1.3002547]
 [1.4062976 2.812158 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.7362834  -0.9395797 ]
 [ 0.4465999   0.99998003]], shape=(2, 2), dtype=float32)


In [ ]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c, a)  # automatic gradient calculation
  print(dc_da)

tf.Tensor(
[[-0.7362834  -0.9395797 ]
 [ 0.4465999   0.99998003]], shape=(2, 2), dtype=float32)


In [ ]:
b = tf.Variable(b)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_db = tape.gradient(c, b)  # automatic gradient calculation
  print(dc_db)

tf.Tensor(
[[0.6766733  0.34233046]
 [0.8947337  0.00631675]], shape=(2, 2), dtype=float32)


In [ ]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a)
  d2c_da2 = outer_tape.gradient(dc_da, a)
  print(d2c_da2)   # double differentiation

tf.Tensor(
[[4.0954906e-01 9.0128481e-02]
 [5.6925970e-01 1.4156103e-05]], shape=(2, 2), dtype=float32)


Lets take an example of Hyperbolic Tan function (tanh) and try to get its derivative.


![alt text](https://mathworld.wolfram.com/images/interactive/TanhReal.gif)

In [ ]:
tf.tanh(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9640276>

In [ ]:
import math

def tanh(x):
    return tf.tanh(x)

def get_gradient(x, activation_function):
    with tf.GradientTape() as gt:
        y = activation_function(x)

        gradient = gt.gradient(y, x).numpy()

    return gradient

x = tf.Variable(-4.59)
gradient = get_gradient(x,tanh)

print('{0} is the gradient of tanh with x={1}'.format(gradient, x.numpy()))

0.00041218323167413473 is the gradient of tanh with x=-4.590000152587891


### An end-to-end example: linear regression
So far we have learned that TensorFlow is a Numpy-like library that is GPU or TPU accelerated, with automatic differentiation. Time for an end-to-end example: let's implement a linear regression.

In [ ]:
input_dim = 2
output_dim = 1
learning_rate = 0.01 # subject to change

# This is our weight matrix
w = tf.Variable(tf.random.uniform(shape=(input_dim, output_dim))) # parameters, equal to theta
# This is our bias vector
b = tf.Variable(tf.zeros(shape=(output_dim,))) # intercept

def compute_predictions(features): # define hypothesis
  return tf.matmul(features, w) + b

def compute_loss(labels, predictions): # define MSE
  return tf.reduce_mean(tf.square(labels - predictions))

def train(x, y): # training and updating through GD updates
  with tf.GradientTape() as tape:
    predictions = compute_predictions(x) # y_pred or y hat
    loss = compute_loss(y, predictions)  # loss returned
    dloss_dw, dloss_db = tape.gradient(loss, [w, b]) # gradient w.r.t. w and b
  w.assign_sub(learning_rate * dloss_dw) # reassign weights
  b.assign_sub(learning_rate * dloss_db) # reassign bias
  return loss

In [ ]:
# Homework.
'''To generate data and utilize the above code to run a simple linear regression.'''
tol = 1e-3
# write function for predict()
# write a R2 and adjusted R2 score metric
# write a loop and stop training when tolerance condition is met

In [ ]:
# numpy and random function create your own data.

x1 = [10 to 50] # 100 points
x2 = [25 to 100] # 100 points
y = w1.x1 + w2x2 + 50 * noise # data generation

# def r2(y_pred, y_true):
#     return 1- (sum(np.pow((y_pred-y_true),2))/sum(np.pow((mean(y_true)-y_true),2))


SyntaxError: ignored

**Going fast with graphs**

Literally all we need to do is add the tf.function decorator on it

In [ ]:
# dummy code
@tf.function
def train_on_batch(x, y):
  with tf.GradientTape() as tape:
    predictions = compute_predictions(x)
    loss = compute_loss(y, predictions)
    dloss_dw, dloss_db = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * dloss_dw)
  b.assign_sub(learning_rate * dloss_db)
  return loss

Lets see how fast it could go!

In [ ]:
import timeit
conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
  return conv_layer(image)

image = tf.ones([1, 200, 200, 100])
# warm up
conv_layer(image); conv_fn(image)

no_tf_fn = timeit.timeit(lambda: conv_layer(image), number=10) # tensorflow layer
with_tf_fn = timeit.timeit(lambda: conv_fn(image), number=10) # graph
difference = no_tf_fn - with_tf_fn

print("Without tf.function: ", no_tf_fn)
print("With tf.function: ", with_tf_fn)
print("The difference: ", difference)

print("\nJust imagine when we have to do millions/billions of these calculations")
print("Difference times a billion: ", difference*1000000)